// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package creatingmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CourseService is an autogenerated mock type for the CourseService type
type CourseService struct {
	mock.Mock
}

// CreateCourse provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *CourseService) CreateCourse(_a0 context.Context, _a1 string, _a2 string, _a3 string) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
